tester_type: # livetest, backtest
livetest_test: # set to False if you want to do a real rebalance
exchange: # binance

tick_duration: # seconds
rebalance_ticks: # 1hr
open_order_check_ticks: # 10m
candle_time: # 1m, 5m, 15m, 30m, 1h, 2h, 4h, 1d, 1w, 1M

open_order_time_limit:
minimum_btc_order:
transaction_fee:

# Telegram
telegram_on: # set telegram bot on
username:
telegram_ticks: # seconds
